/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as NNoRouteImport } from './routes/n/$no'
import { Route as RSlugRouteImport } from './routes/r/$slug'
import { Route as UUserIdRouteImport } from './routes/u/$userId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMediaBlobRouteImport } from './routes/api/media/blob'
import { Route as ApiMediaConfigRouteImport } from './routes/api/media/config'
import { Route as ApiMediaSignRouteImport } from './routes/api/media/sign'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const NNoRoute = NNoRouteImport.update({
  id: '/n/$no',
  path: '/n/$no',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaBlobRoute = ApiMediaBlobRouteImport.update({
  id: '/api/media/blob',
  path: '/api/media/blob',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaConfigRoute = ApiMediaConfigRouteImport.update({
  id: '/api/media/config',
  path: '/api/media/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSignRoute = ApiMediaSignRouteImport.update({
  id: '/api/media/sign',
  path: '/api/media/sign',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/messages': typeof MessagesRoute
  '/rooms': typeof RoomsRoute
  '/saved': typeof SavedRoute
  '/stories': typeof StoriesRoute
  '/tools': typeof ToolsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/n/$no': typeof NNoRoute
  '/r/$slug': typeof RSlugRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/blob': typeof ApiMediaBlobRoute
  '/api/media/config': typeof ApiMediaConfigRoute
  '/api/media/sign': typeof ApiMediaSignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/messages': typeof MessagesRoute
  '/rooms': typeof RoomsRoute
  '/saved': typeof SavedRoute
  '/stories': typeof StoriesRoute
  '/tools': typeof ToolsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/n/$no': typeof NNoRoute
  '/r/$slug': typeof RSlugRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/blob': typeof ApiMediaBlobRoute
  '/api/media/config': typeof ApiMediaConfigRoute
  '/api/media/sign': typeof ApiMediaSignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/messages': typeof MessagesRoute
  '/rooms': typeof RoomsRoute
  '/saved': typeof SavedRoute
  '/stories': typeof StoriesRoute
  '/tools': typeof ToolsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/n/$no': typeof NNoRoute
  '/r/$slug': typeof RSlugRoute
  '/u/$userId': typeof UUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/blob': typeof ApiMediaBlobRoute
  '/api/media/config': typeof ApiMediaConfigRoute
  '/api/media/sign': typeof ApiMediaSignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/friends'
    | '/login'
    | '/me'
    | '/messages'
    | '/rooms'
    | '/saved'
    | '/stories'
    | '/tools'
    | '/api/rtc'
    | '/n/$no'
    | '/r/$slug'
    | '/u/$userId'
    | '/api/auth/$'
    | '/api/media/blob'
    | '/api/media/config'
    | '/api/media/sign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/friends'
    | '/login'
    | '/me'
    | '/messages'
    | '/rooms'
    | '/saved'
    | '/stories'
    | '/tools'
    | '/api/rtc'
    | '/n/$no'
    | '/r/$slug'
    | '/u/$userId'
    | '/api/auth/$'
    | '/api/media/blob'
    | '/api/media/config'
    | '/api/media/sign'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/friends'
    | '/login'
    | '/me'
    | '/messages'
    | '/rooms'
    | '/saved'
    | '/stories'
    | '/tools'
    | '/api/rtc'
    | '/n/$no'
    | '/r/$slug'
    | '/u/$userId'
    | '/api/auth/$'
    | '/api/media/blob'
    | '/api/media/config'
    | '/api/media/sign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FriendsRoute: typeof FriendsRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  MessagesRoute: typeof MessagesRoute
  RoomsRoute: typeof RoomsRoute
  SavedRoute: typeof SavedRoute
  StoriesRoute: typeof StoriesRoute
  ToolsRoute: typeof ToolsRoute
  ApiRtcRoute: typeof ApiRtcRoute
  NNoRoute: typeof NNoRoute
  RSlugRoute: typeof RSlugRoute
  UUserIdRoute: typeof UUserIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaBlobRoute: typeof ApiMediaBlobRoute
  ApiMediaConfigRoute: typeof ApiMediaConfigRoute
  ApiMediaSignRoute: typeof ApiMediaSignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$no': {
      id: '/n/$no'
      path: '/n/$no'
      fullPath: '/n/$no'
      preLoaderRoute: typeof NNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/blob': {
      id: '/api/media/blob'
      path: '/api/media/blob'
      fullPath: '/api/media/blob'
      preLoaderRoute: typeof ApiMediaBlobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/config': {
      id: '/api/media/config'
      path: '/api/media/config'
      fullPath: '/api/media/config'
      preLoaderRoute: typeof ApiMediaConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/sign': {
      id: '/api/media/sign'
      path: '/api/media/sign'
      fullPath: '/api/media/sign'
      preLoaderRoute: typeof ApiMediaSignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FriendsRoute: FriendsRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  MessagesRoute: MessagesRoute,
  RoomsRoute: RoomsRoute,
  SavedRoute: SavedRoute,
  StoriesRoute: StoriesRoute,
  ToolsRoute: ToolsRoute,
  ApiRtcRoute: ApiRtcRoute,
  NNoRoute: NNoRoute,
  RSlugRoute: RSlugRoute,
  UUserIdRoute: UUserIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaBlobRoute: ApiMediaBlobRoute,
  ApiMediaConfigRoute: ApiMediaConfigRoute,
  ApiMediaSignRoute: ApiMediaSignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
